FROM python:3.10

WORKDIR /web-server
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /web-server/requirements.txt
COPY . /web-server/

ENTRYPOINT ["uvicorn", "web-server.main:web-server", "--host", "0.0.0.0", "--port", "8080"]